### ISSUE TITLE
What do you like Apple or Samsung?

### ISSUE THREAD

**Issue by paifonhp** [paifonhp/LadyElizabethP#4]
give me a reason.

**Comment by nuknik** [comment]
Up to me

**Comment by hirn23** [comment]
don't like anything

**Comment by paifonhp** [comment]
What do you mean?

**Comment by 550108020045** [comment]
I like apple but i use iphone and com(mac)    I LOVE APPLE <3

**Comment by popza1112** [comment]
i like  linux distro desktop

**Comment by hirn23** [comment]
and i don't like E'nuknik ,she so stupid

**Comment by 550108020045** [comment]
#hirn23 me too

**Comment by paifonhp** [comment]
same same

**Comment by popza1112** [comment]
no i don'n like pat very much. kill him

**Comment by paifonhp** [comment]
kill him ? are you serious?

**Comment by 550108020045** [comment]
help paifonhp !!

**Comment by popza1112** [comment]
kill u frist

**Comment by paifonhp** [comment]
no. I'm Captain. I fair to everyone.

**Comment by 550108020045** [comment]
so sad Hooooooooooo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by paifonhp** [comment]
ho ho ho~ Merry X'Mas ~~

**Comment by 550108020045** [comment]
EIEI

**Comment by popza1112** [comment]
tonight u dress a nightmare
